<?php

/**
 * @file
 * To alter system information page.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter for 'system form'.
 */
function site_info_api_form_system_site_information_settings_alter(&$form, FormStateInterface $form_state, $form_id) {

  // Get api key from system varable.
  $siteApiKey = \Drupal::config('site_info.settings')->get('siteapikey');

  $form['site_api_key'] = [
    '#type' => 'textfield',
    '#title' => t('Site API Key'),
    '#size' => 40,
    '#default_value' => ($siteApiKey) ? $siteApiKey : t('No API Key yet'),
    '#description' => t('The value entered for this field saved as system variable.'),
  ];

  // Change value of submit button.
  if ($siteApiKey) {
    $form['actions']['submit']['#value'] = 'Update Configuration';
  }
  $form['actions']['submit']['#submit'][] = 'site_info_settings_form_submit';

}

/**
 * Custom submit handler for site information form.
 */
function site_info_settings_form_submit(&$form, FormStateInterface $form_state) {

  // Store site api key into the system variable.
  \Drupal::configFactory()->getEditable('site_info.settings')
    ->set('siteapikey', $form_state->getValue('site_api_key'))
    ->save();
  drupal_set_message(t('Site API Key has been saved with %siteApiKey',
    array('%siteApiKey' => \Drupal::config('site_info.settings')->get('siteapikey'))), 'status', TRUE);
}
